services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-service
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    networks:
      - app_net
      - keycloak_net

networks:
  app_net:
    external: true
  keycloak_net:
    external: true
