spring:
    application:
        name: AdminService
    profiles:
        active: local

server:
    port: 8081

feign:
    client:
        config:
            default:
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: full

